[versions]
kotlin = "2.0.20"
ktlint = "12.1.1"
paper = "1.21.1-R0.1-SNAPSHOT"
paperweight = "1.7.2"
run-task = "2.3.1"
shadow = "8.3.2"

[libraries]


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
